# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bd89f6465184dcf50c586500f41bc6ba"
name = "Catalogr"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-04"
